teloxide/teloxide-core

- src/errors.rs
- src/lib.rs
- src/local_macros.rs
- src/net/mod.rs
- src/net/telegram_response.rs
- Enhance documentation
- Merge `ApiErrorKind` and `KnownApiErrorKind` into `ApiError`
- Small internal changes
> Cleanup errors

- src/types/message.rs
See https://github.com/teloxide/teloxide/issues/306 (fixes it in `-core`﻿)
> make MessageDice::dice public

- src/local_macros.rs
See https://github.com/teloxide/teloxide/issues/310﻿
> Implement IntoIterator-based convert for impl_payload! macro

- Cargo.toml
- src/types.rs
- src/types/non_telegram_types/semiparsed_vec.rs
- src/types/update.rs
- `non_strict_vec.rs` -> `semiparsed_vec.rs`
- Add `Update::try_parse`
> Fix SemiparsedVec

- src/types/message.rs
Port of https://github.com/teloxide/teloxide/pull/343
> Make MediaContact::contact public

- CHANGELOG.md
- src/payloads/get_chat_administrators.rs
Fix `GetChatAdministrators` output type `ChatMember` => `Vec<ChatMember>`
Thanks, @Aloxaf!
> fix `GetChatAdministrators`

- CHANGELOG.md
- src/payloads/send_chat_action.rs
Fixes https://github.com/teloxide/teloxide/issues/359
> Fix SendChatAction return type

- CHANGELOG.md
- src/types/chat_member.rs
- Add `Deref` impl for `ChatMember` to allow calling kind's methods directly
- Add is_* methods to `ChatMember`
- Make privileges checks easier to use
- Make rights checks easier to use
- Add `ChatMemberKind::is_anonymous` method
> Refactor ChatMember methods

- src/errors.rs
Fixes teloxide/teloxide#371, fixes teloxide/teloxide#372
> Add NotEnoughRightsToManagePins and BotKickedFromSupergroup errors

- CHANGELOG.md
Sorry, forgot to update the changelog. Reflect changes made in #84
> Update changelog with new API errors info

- CHANGELOG.md
- src/types/chat.rs
- src/types/message.rs
- src/types/update.rs
- Add `Chat` getters
- Add missing `Chat::message_auto_delete_time` field (tba 5.1)
- Improve `Message::url`
> Add `Chat` getters, misssing field and improve `Message::url`

- README.md
Before: ![image](https://user-images.githubusercontent.com/38225716/117552360-8714e600-b053-11eb-8ed5-792da871c0d0.png)
After: ![image](https://user-images.githubusercontent.com/38225716/117552364-9005b780-b053-11eb-979c-a025331b0e02.png)
> Fixup docs badge

- src/requests/payload.rs
- src/requests/request.rs
- src/requests/requester.rs
The attribute was recently renamed
> Use proper notable_trait attr

- Cargo.toml
See [docs](https://docs.rs/about/metadata) and [discord disscussion](https://discord.com/channels/442252698964721669/541978667522195476/840689577005940766).
> Fix docs.rs metadata

- CHANGELOG.md
- src/adaptors/parse_mode.rs
- src/adaptors/throttle.rs
Resolves https://github.com/teloxide/teloxide/issues/293
> Adaptor info

- CHANGELOG.md
- Cargo.toml
- src/adaptors/auto_send.rs
- src/adaptors/cache_me.rs
- src/adaptors/parse_mode.rs
- src/adaptors/throttle.rs
- src/bot/api.rs
- src/local_macros.rs
- src/payloads/answer_callback_query.rs
- src/payloads/create_chat_invite_link.rs
- src/payloads/edit_chat_invite_link.rs
- src/payloads/kick_chat_member.rs
- src/payloads/restrict_chat_member.rs
- src/payloads/send_invoice.rs
- src/payloads/send_poll.rs
- src/payloads/set_webhook.rs
- src/requests/requester.rs
- src/types.rs
Resolves https://github.com/teloxide/teloxide/issues/370, resolves https://github.com/teloxide/teloxide/issues/377
> Use `url::Url` for urls, use `chrono::DateTime<Utc>` for dates

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
- src/types/photo_size.rs
- src/types/reply_markup.rs
> Prepare for 0.3 release

- CHANGELOG.md
- Cargo.toml
- src/requests/has_payload.rs
- src/requests/request.rs
- src/requests/requester.rs
This allows to use different adaptors depending on runtime context.
> impl `HasPayload`, `Request` and `Requester` for `either::Either`

- CHANGELOG.md
- Cargo.toml
- src/adaptors.rs
- src/adaptors/trace.rs
- src/lib.rs
- src/requests/requester_ext.rs
Resolves teloxide/teloxide#415
> Add `Trace` bot adaptor

- CHANGELOG.md
- Cargo.toml
- examples/erased.rs
- examples/self_info.rs
- src/adaptors.rs
- src/adaptors/erased.rs
- src/lib.rs
- src/requests/request.rs
- src/requests/requester_ext.rs
Resolves https://github.com/teloxide/teloxide/issues/393
> Add tools for Bot/`Request` type erasure

- CHANGELOG.md
- src/errors.rs
Resolves https://github.com/teloxide/teloxide/issues/430
> Add `EditedMessageIsTooLong` error

- src/types/message.rs
> Fixed url formatting for private groups and some typos

- CHANGELOG.md
- src/adaptors/throttle.rs
- src/types/chat_id.rs
- Fix limit check (bug inroduced by [`d58b21c`](https://github.com/teloxide/teloxide-core/commit/d58b21c42f532ffe77c554c881ed8e029f663998#diff-f393cb507820637038d1364ad24d599b911635e87552ca1ad51c5e4f567118a7R267-R273))
- Correct limits for channels (apparently channels have lower limits)
Fixes https://github.com/teloxide/teloxide/issues/449
> Fix `Throttle` adaptor

- CHANGELOG.md
- src/errors.rs
- src/net/request.rs
- src/net/telegram_response.rs
This is inspired by this discussion in our chat: [teloxide/5437](https://t.me/teloxide/5437)
Hopefully, this will make code that deals with errors nicer & easier to read.
> Refactor errors

- src/errors.rs
Pull requests #134 and #135 conflict with each other (see failing CI on `master` branch)
> Fix conflict between PRs 

- CHANGELOG.md
- Cargo.toml
- src/serde_multipart/mod.rs
- src/serde_multipart/serializers.rs
Closes https://github.com/teloxide/teloxide/issues/473
> Fix message entity serialization

- CHANGELOG.md
- src/payloads/copy_message.rs
https://github.com/WaffleLapkin/tg-methods-schema/pull/42
> re-run payloads codegen

- CHANGELOG.md
- src/types/encrypted_credentials.rs
- src/types/message.rs
Fixes https://github.com/teloxide/teloxide/issues/427
> Fix deserialization of chat migrations

- .github/workflows/ci.yml
- rust-toolchain.toml
- src/lib.rs
- Pin tooling in the CI to a specific version
- Suppress clippy
This is similar to https://github.com/teloxide/teloxide/pull/467
> pin tooling

- CHANGELOG.md
- src/types/message.rs
Fixes https://github.com/teloxide/teloxide/issues/481
> Fix deserialization of `MediaKind::Venue`

- CHANGELOG.md
- src/types/message.rs
- src/types/update.rs
- src/types/user.rs
- Add `User::is_anonymous` and `User::is_channel` functions
- Refactor forwarded messages
Fixes https://github.com/teloxide/teloxide/issues/419
cc @Mr-Andersen
> fix some message deserialization bugs

- CHANGELOG.md
- src/errors.rs
Resolves https://github.com/teloxide/teloxide/issues/485
> Add `ApiError::NotEnoughRightsToChangeChatPermissions`

- CHANGELOG.md
- Cargo.toml
- src/types/chat_permissions.rs
This allows operating with permissions naturaly
> Make `ChatPermissions` into bitflags

- CHANGELOG.md
- src/types/chat.rs
- src/types/message.rs
- src/types/update.rs
This was forgotten during TBA 5.5 update.
> Add `Chat::has_protected_content`

- README.md
- src/payloads/copy_message.rs
- src/payloads/forward_message.rs
- src/payloads/send_animation.rs
- src/payloads/send_audio.rs
- src/payloads/send_contact.rs
- src/payloads/send_dice.rs
- src/payloads/send_document.rs
- src/payloads/send_game.rs
- src/payloads/send_invoice.rs
- src/payloads/send_location.rs
- src/payloads/send_media_group.rs
- src/payloads/send_message.rs
- src/payloads/send_photo.rs
- src/payloads/send_poll.rs
- src/payloads/send_sticker.rs
- src/payloads/send_venue.rs
- src/payloads/send_video.rs
- src/payloads/send_video_note.rs
- src/types/message_entity.rs
- src/types/parse_mode.rs
https://core.telegram.org/bots/api#december-30-2021
> Add support for TBA 5.6

- src/net.rs
Fixes https://github.com/teloxide/teloxide/issues/491
> Remove redundant settings from `default_reqwest_settings`

- CHANGELOG.md
- src/types/webhook_info.rs
`String` -> `std::net::IpAddr`
> Make `WebhookInfo::ip_address` typed

- CHANGELOG.md
- src/types/webhook_info.rs
One day I'll make everything typed
> Make `WebhookInfo::allowed_updates` typed

- CHANGELOG.md
- src/errors.rs
Fixes https://github.com/teloxide/teloxide/issues/538
Fixes https://github.com/teloxide/teloxide/issues/540
> Add `WrongFileIdOrUrl` and `FailedToGetUrlContent` errors

- src/types/chat_id.rs
This fixes handling of "big" (>32 bit) chat/user/channel ids in some internals.
> Fix chat unmark

- .github/workflows/ci.yml
https://github.com/teloxide/teloxide/pull/566#issuecomment-1077539269
> Pin nightly compiler version in CI

- src/adaptors/throttle.rs
- src/lib.rs
> Fix some more typos

- CHANGELOG.md
- src/types/me.rs
- src/types/user.rs
- src/types/user_id.rs
- Add `UserId::{url, is_anonymous, is_channel, is_telegram}` functions
- Add `User::{tme_url, preferably_tme_url}` functions
- Add `Me::username` and `Deref<Target = User>` impl for `Me`
- "override" `mention` and `tme_url` on `Me`
> Add some convenience methods to `User` and `Me`

- CHANGELOG.md
- src/types/allowed_update.rs
> Add `AllowedUpdate::ChatJoinRequest`

- CHANGELOG.md
- Cargo.toml
> Prepare 0.5.0 release

- CHANGELOG.md
- Cargo.toml
- README.md
- netlify.toml
- src/lib.rs
> Release v0.5.1

- Cargo.toml
Context: https://t.me/teloxide_ru/337.
> Update `reqwest` to v0.11.10

- CHANGELOG.md
- src/types/message_entity.rs
Issue: https://github.com/teloxide/teloxide/issues/547#issuecomment-1107530302
> Add method `MessageEntity::user_mention`

- CHANGELOG.md
- src/types/message_entity.rs
> Add shortcuts for other kinds of entities

- CHANGELOG.md
- src/types/chat_member.rs
- Fix deserialization of ChatMemberStatus
- Add `is_*` methods to `ChatMemberStatus`
> Add `ChatMemberStatus::is_*` methods

- CHANGELOG.md
- Cargo.toml
> Release `teloxide-core` v0.6.1

- CHANGELOG.md
- Cargo.toml
Fixes https://github.com/teloxide/teloxide/issues/650
> fix: could not find `codec` in `tokio_util`

- CHANGELOG.md
- src/types/chat.rs
Fixes https://github.com/teloxide/teloxide/issues/652
> Fix `ChatPrivate` serialization

- CHANGELOG.md
- Cargo.toml
No more problems with `tokio-util` (probably)!
> Release `0.6.2`

- src/requests/requester_ext.rs
> Fix unused import when throttle feature is not enabled

- CHANGELOG.md
- src/types/chat.rs
- src/types/update.rs
Fixes https://github.com/teloxide/teloxide/issues/107 🎉
> Remove `ChatPrivate::type_`

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
experiment with CI
This PR:
- enables caching (that makes testing twice as fast)
- adds checking of examples
- adds checking of documentation
> [experiment] refactor ci

- src/local_macros.rs
the compiler bug was fixed a while ago
> remove a fixme

- CHANGELOG.md
- src/types/sticker.rs
- src/types/sticker_set.rs
I think it's a lot nicer this way.
> Add `StickerKind`

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
> Bump verson to `0.7`

- CHANGELOG.md
- Cargo.toml
`0.7.0` -> `0.7.1` w/ a couple of small fixes
> dump version

- src/types/keyboard_button.rs
I think the wording is not perfect, maybe someone has ideas how to improve this further?
> Write documentation for `ButtonRequest`

- CHANGELOG.md
- src/bot/api.rs
Resolves https://github.com/teloxide/teloxide/issues/698
> Fix `SetWebhook` request: make it multipart

- CHANGELOG.md
- src/types/input_sticker.rs
> Fix serialization of video stickers

- CHANGELOG.md
- src/net/download.rs
- src/types/animation.rs
- src/types/audio.rs
- src/types/document.rs
- src/types/file.rs
- src/types/passport_file.rs
- src/types/photo_size.rs
- src/types/sticker.rs
- src/types/video.rs
- src/types/video_note.rs
- src/types/voice.rs
See [code style](https://github.com/teloxide/teloxide/blob/ba545c35e84cdd348a01afe37c744faeca22afbd/CODE_STYLE.md#naming).
> Remove `file_` prefix from `File` fields
