Cargo.toml
src/bot/mod.rs
src/local_macros.rs
src/net/mod.rs
src/net/request.rs
src/requests/json.rs
src/requests/mod.rs
src/requests/multipart.rs
src/requests/request.rs
src/serde_multipart/serializers.rs

Implement default Bot's requests structs. 
This is part of requests redisign.﻿
Those structs will be returned from `<Bot as Requestor>` methods once we'll implement Requestor.
Note: we create induvidual structs for Send/SendRef so we could use exhastential types on nightly (`feature(type_alias_impl_trait)`) while using `Box`ing on stable.
﻿

implement default Bot's {Json,Multipart}Request

---

Cargo.toml
src/bot/api.rs
src/bot/cache_me.rs
src/bot/mod.rs
src/lib.rs
src/payloads/get_me.rs
src/payloads/mod.rs
src/payloads/setters.rs
src/prelude.rs
src/requests/has_payload.rs
src/requests/json.rs
src/requests/mod.rs
src/requests/multipart.rs
src/requests/payload.rs
src/requests/request.rs
src/requests/requester.rs
src/requests/requester_ext.rs

- remove `AsMut`/`AsRef` bounds because of a compiler bug
- add `Requester` trait and `GetMe` payload
- implement `get_me` caching
- add `:std::error::Error` bound on `Request::Err`
Closes https://github.com/teloxide/teloxide/issues/278

Requests redisign part 2

---

src/types/chat_member.rs

- Replace a bunch of `Option<_>` fields with `hatMemberKind`
- Remove setters (users are not expected to create this struct)
- Add getters
Closes https://github.com/teloxide/teloxide/issues/174

Refactor ChatMember

---

Cargo.toml
src/bot/api.rs
src/bot/auto_send.rs
src/bot/cache_me.rs
src/bot/limits.rs
src/bot/mod.rs
src/lib.rs
src/payloads/mod.rs
src/payloads/send_message.rs
src/payloads/setters.rs
src/requests/request.rs
src/requests/requester.rs
src/requests/requester_ext.rs

This adds `Throttling` bot adaptor which can automatically throttle when telegram limits are exceeded.
Also adds `send_message` to `Requestor`.
Resolves teloxide/teloxide#164

Request throttling (limits)

---

src/bot/api.rs
src/bot/auto_send.rs
src/bot/cache_me.rs
src/bot/limits.rs
src/local_macros.rs
src/requests/request.rs
src/requests/requester.rs

- Add `Err` associated type to `Requester`, containing all requests to have the same `Err`.
- Add `core::marker::Send` bound for `Request::{Err,Send,SendRef}` associated types.
Pros: easier to write user code, cons: harder to write teloxide itself.

Make the trait bounds in Request{,er} stricter

---

src/net/telegram_response.rs

serde-rename `TelegramResponse::reponse` to `result` (fixes regression entroduced in #13)

Fix telegram response

---

src/bot/api_url.rs
src/bot/mod.rs
src/net/download.rs
src/net/mod.rs
src/net/request.rs

Recently, telegram has published [Telegram Bot API Server] - HTTP API <->
MTPROTO proxy which is used internally by telegram. Now it's possible to run
the server locally.
However currently it's not possible to use teloxide with such local server,
because API url is hardcoded into teloxide.
This commit makes _internall_ changes to allow setting the API url. It doesn't
yet allow to set the url from user code (i.e.: no changes in public API), in my
opinion such additions are blocked on some bot refactorings.
`Bot::api_url` is made `Option<Arc<str>>` to minimize costs in case of 'default
url' (probably the most common case).
Progress of this issue is tracked in https://github.com/teloxide/teloxide/issues/317
[Telegram Bot API Server]: https://github.com/tdlib/telegram-bot-api

Add internal ability to change API url

---

src/adaptors.rs
src/adaptors/parse_mode.rs
src/bot/api.rs
src/bot/mod.rs
src/lib.rs
src/requests/requester_ext.rs

- Move default parse mode to an adaptor
- Remove bot builder (it's not usefull anymore, since parse_mode is moved away)
- Undeprecate bot constructors

Refactor Bot for a bit

---

src/adaptors/auto_send.rs
src/adaptors/cache_me.rs
src/adaptors/parse_mode.rs
src/adaptors/throttle.rs
src/bot/download.rs
src/lib.rs
src/local_macros.rs
src/net/download.rs
src/net/mod.rs
src/net/telegram_response.rs
src/requests/multipart.rs
src/types/file.rs

- Make `net` module public
- Move `Bot::download_file{,_stream}` methods to a new `Download` trait
- Add `download_forward` macro to forward `Download` impls (priv)
- Impl `Download` for all bot adaptors & the `Bot` itself
- Change return type of `download_file_stream` — return `Stream<Result<Bytes>>``,
instead of `Future<Result<Stream<Result<Bytes>>>>``
- Add `api_url` param to standalone versions of `download_file{,_stream}`
- Make `net::{TELEGRAM_API_URL, download_file{,_stream}}` pub
- Small documentation changes

Refactor file downloading

---

Cargo.toml
netlify.toml
src/lib.rs

Normalize docs

---

src/requests/requester.rs

This PR adds
```rust
impl<B: Requester> Requester for D<B> { ... }
```
where `D<_>` is `&_`, `&mut _`, `Box<_>`, `Arc<_>` and `Rc<_>`.

Add forward-to-deref Requester impls

---

Cargo.toml

This was teloxide-based applications can be easily compiled for musl
targets.

Support rustls

---

CHANGELOG.md
src/types/inline_keyboard_markup.rs
src/types/reply_keyboard_markup.rs
src/types/reply_keyboard_remove.rs
src/types/reply_markup.rs

This PR tries to make using ReplyMarkup less noisy. It
- Renames `ReplyMarkup::{InlineKeyboardMarkup => InlineKeyboard, ReplyKeyboardMarkup => Keyboard, ReplyKeyboardRemove => KeyboardRemove}`
- Adds `inline_kb`, `keyboad`, `kb_remove` and `force_reply` `ReplyMarkup`
consructors
- Renames `ReplyKeyboardMarkup` => `KeyboardMarkup`
- Renames `ReplyKeyboardRemove` => `KeyboardRemove`
- Removes useless generic param from `ReplyKeyboardMarkup::new` and
`InlineKeyboardMarkup::new`
- Changes parameters order in `ReplyKeyboardMarkup::append_to_row` and
`InlineKeyboardMarkup::append_to_row`
resolves https://github.com/teloxide/teloxide/issues/311

refactor reply markup

---

CHANGELOG.md
Cargo.toml
src/prelude.rs
src/types/reply_markup.rs

- doc(no_inline) prelude reexports
- Fix typo: `ReplyMarkup::{keyboad => keyboard}`
- Bump version (0.2.1 => 0.2.2)

(For instant release) Fix typo: `ReplyMarkup::{keyboad => keyboard}`

---

CHANGELOG.md
Cargo.toml

The reqwest dependency brings the `native-tls` in as part of its default features, even if the `rustls` feature is specified. Adding `default-features = false` fixes the problem.

fix reqwest dependency features

---

CHANGELOG.md
src/payloads/leave_chat.rs
src/payloads/pin_chat_message.rs
src/payloads/set_chat_description.rs
src/payloads/set_chat_photo.rs
src/payloads/set_chat_title.rs
src/payloads/unpin_all_chat_messages.rs
src/payloads/unpin_chat_message.rs

Fix return types of `LeaveChat`, `PinChatMessage`, `SetChatDescription`, `SetChatPhoto`, `SetChatTitle`, `UnpinAllChatMessages` and `UnpinChatMessage`: `String` => `True`.
Thanks, @Aloxaf for finding & fixing typos in the schema.

Fix return types of methods

---

CHANGELOG.md
src/bot.rs
src/net.rs

This function can help when users want to set up their own client setting for
one reason or another, since settings set by the function, are required for
stable work.
This function was previously private and named `sound_bot`. The old name was
confusing since safety and soundness are used in the Rust context almost
entirely for `unsafe` code, UB & co. So I've changed the name to a more
descriptive one.

Add `net::default_reqwest_settings` function

---

src/requests/has_payload.rs
src/types/audio.rs
src/types/chat_member.rs
src/types/user.rs

See https://github.com/teloxide/teloxide-core/pull/11

Resolve FIXME in `HasPayload`: we've decided to not add `As{Mut,Ref}` bounds

---

CHANGELOG.md
src/net/telegram_response.rs

According to https://core.telegram.org/bots/api#making-requests, now the error struct is contained in the `parameters` field.
In this Pull Request,  the field is renamed to adapt to this change.

telegram_response: fix issue `retry_after` and `migrate_to_chat_id` handling

---

src/payloads/get_my_commands.rs
src/payloads/set_my_commands.rs

Fix return types of `get_my_commands` (`u32` => `True`) and `set_my commands` (`u32` => `Vec<BotCommand>`).
Fixes https://github.com/teloxide/teloxide/issues/402
See also: https://github.com/WaffleLapkin/tg-methods-schema/pull/38

Fix rt-tys of `{get,set}_my_commands` methods

---

CHANGELOG.md
src/adaptors/throttle.rs

Add a `#[non_exhaustive]` `Settings` builder struct. Replace `with_queue_full_fn` and `spawn_with_queue_full_fn` with `with_settings` and `spawn_with_settings`.
This allows adding more settings in the future without breaking changes.

Make `Throttle` settings more extendable

---

CHANGELOG.md
Cargo.toml
src/adaptors.rs
src/lib.rs
src/requests/payload.rs
src/requests/request.rs
src/requests/requester.rs
src/requests/requester_ext.rs

- Use `cfg(dep_docsrs)` to allow building docs properly as a dependency
- Remove `Self: 'static` bound on `RequesterExt::throttle`

0.3.1 hotfix

---

CHANGELOG.md
Cargo.toml
src/lib.rs

The `min_type_alias_impl_trait` feature was removed in faviour of `type_alias_impl_trait`.
The problem was noticed in https://github.com/teloxide/teloxide/pull/421/checks?check_run_id=3214192304.

Fix compilation with `nigthly` feature

---

src/adaptors/throttle.rs

The issue in fixme says to use `tokio::task::unconstrained`.

Use `tokio::task::unconstrained` when using `.now_or_never()` to prevent some problems I guess

---

CHANGELOG.md
src/payloads/ban_chat_member.rs
src/types.rs
src/types/chat_member.rs
src/types/non_telegram_types/until_date.rs

- Patch `BanChatMember::until_date`: `u64` -> `DateTime<Utc>`
- Add `UntilDate` enum and use it for `{Restricted, Banned}::until_date`

`until_date` fixes

---

CHANGELOG.md
src/types/poll.rs

Params [correct_option_id](https://github.com/WaffleLapkin/tg-methods-schema/blob/b7e0ddbde7a8f3a53720531370f49b51c73e295f/schema.ron#L1517) and [open_period](https://github.com/WaffleLapkin/tg-methods-schema/blob/b7e0ddbde7a8f3a53720531370f49b51c73e295f/schema.ron#L1541) of `sendPoll` method use smaller types, because `correct_option_id` is in the range 0..9 and fits in u8, and `open_period` in the range 5..600 can be u16. As I understand it, this is just a typo mistake.

Fix type of `Poll::{correct_option_id,open_period}` fields: `i32` => `u8` and `u16`

---

src/adaptors/auto_send.rs
src/adaptors/cache_me.rs
src/adaptors/erased.rs
src/adaptors/parse_mode.rs
src/adaptors/throttle.rs
src/adaptors/trace.rs

As discussed in the chat, these derives from the main Bot are missing on the adapters making them incompatible.

fix: Add missing derive(Debug) on adapters

---

src/lib.rs

We've previously released a version of `teloxide-core` that had `dbg!` in it, so it seems like a good idea to enable these warnings to prevent this from happening again.
Also, remove an old `#![allow]` that was used to suppress a Clippy bug that has been fixed since then.

Enable clippy to warn on dbg/print usage

---

CHANGELOG.md
src/types/message.rs

According to the `media` argument type of [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup) method, we can know that these media may be sent in a group: `MediaAudio`, `MediaDocument`, `MediaPhoto`, `MediaVideo`.
You can also send a group of files or audios to [@JsonDumpBot](https://t.me/JsonDumpBot) and you can see the `media_group_id` field in the json dump of the reply.
This PR added the missing field `media_group_id` to struct `MediaDocument` and struct `MediaAudio`.

Add the missing field `media_group_id` to `MediaDocument` & `MediaAudio`

---

CHANGELOG.md
src/types/message_id.rs

MRE:
```rust
use teloxide::prelude::*;
#[tokio::main]
async fn main() {
let bot = Bot::from_env().auto_send();
teloxide::repl(bot, |cx| async move {
cx.requester
.copy_message(cx.update.chat_id(), cx.update.chat_id(), cx.update.id)
.send()
.await
.unwrap();
respond(())
})
.await;
}
```
unwrap panic:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidJson(Error("data did not match any variant of untagged enum TelegramResponse", line: 0, column: 0))', src\main.rs:12:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
response:
```json
{"ok":true,"result":{"message_id":123}}
```
The docs of `copyMessage` method: https://core.telegram.org/bots/api#copymessage

Fix the incorrect response type of `CopyMessage` method

---

CHANGELOG.md
src/types/input_media.rs

The docs of `ImputMediaPhoto`: https://core.telegram.org/bots/api#inputmediaphoto

Add the missing method `caption_entities` to `InputMediaPhoto`

---

CHANGELOG.md
src/types/message_entity.rs

MRE:
```rust
use teloxide::{
payloads::SendMessageSetters,
prelude::*,
types::{MessageEntity, MessageEntityKind},
};
#[tokio::main]
async fn main() {
let bot = Bot::from_env().auto_send();
teloxide::repl(bot, |cx| async move {
let entity = MessageEntity::new(MessageEntityKind::Pre { language: None }, 0, 4);
println!("{}\n", serde_json::to_string(&entity).unwrap());
cx.requester
.send_message(cx.update.chat_id(), "test")
.entities(vec![entity])
.await
.unwrap();
respond(())
})
.await;
}
```
unwrap panic:
```
{"type":"pre","language":null,"offset":0,"length":4}
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ApiError { kind: Unknown("Bad Request: can't parse MessageEntity: Field \"language\" must be of type String"), status_code: 400 }', …
```

Skip the `language` field of `MessageEntityKind::Pre` if it is `None`

---

CHANGELOG.md
src/types/message.rs
src/types/voice_chat_ended.rs
src/types/voice_chat_started.rs

Fixes https://github.com/teloxide/teloxide/issues/475

Fix deserialization of `VoiceChat{Started,Ended}` messages

---

CHANGELOG.md
src/types/bot_command_scope.rs

Fixes https://github.com/teloxide/teloxide/issues/486
Welp, I should have tested that `#[serde(rename)]` worked like I thought it did.

Fix serialization of `BotCommandScope::Chat{,Administrators}`

---

src/lib.rs

https://github.com/rust-lang/rust/pull/90502 split `doc_cfg` feature into two, the implication of `doc(cfg)` by `cfg` now depends on `doc_auto_cfg` feature.

Fix `doc(cfg)` implication

---

src/serde_multipart/mod.rs
src/types.rs
src/types/chat_invite_link.rs
src/types/document.rs
src/types/message.rs
src/types/poll.rs
src/types/webhook_info.rs

When calling `Bot::send_document`, I get an error: `InvalidJson(Error("data did not match any variant of untagged enum TelegramResponse", line: 0, column: 0))`.
Also, when compiling my app with freshly cloned teloxide-core, I got compilation error (see the 1st commit).
This PR fixes both problems.

Fix deserializing `Document`

---

src/types.rs
src/types/webhook_info.rs

Currently WebhookInfo fails to parse response like
``` json
{
"url": "",
"has_custom_certificate": false,
"pending_update_count": 0,
"allowed_updates": [
"message"
]
}
```
which according to [telegram docs](https://core.telegram.org/bots/api#getwebhookinfo) is expected when webhook is not set.
One approach is to use custom deserialization method. The other is to use `String` instead of `Option<reqwest::Url>`

fix issue with WebhookInfo not parsing correctly

---

.cargo/config.toml
Cargo.toml
netlify.toml
src/lib.rs

- introduce `docs` alias that does the right thing (tm)
- use `-Zrustdoc-scrape-examples`

Change process of building docs

---

CHANGELOG.md
Cargo.toml
README.md

Finally, 60+ PRs later, new `teloxide-core` release!

Dump version (-> 0.4.0)

---

CHANGELOG.md
src/bot.rs
src/local_macros.rs
src/net/request.rs
src/payloads/get_updates.rs
src/requests/payload.rs

This allows
```rust
bot.get_updates().timeout(60).await?;
```
to succeed even with default client settings.

Add a way for long-running requests to increase network timeout

---

CHANGELOG.md
src/types/message.rs

`.chat.id` is both shorted and doesn't require a function

Deprecate `Message::chat_id`

---

CHANGELOG.md
src/types/update.rs

Add missing enum variants to the `Update::chat()`

---

CHANGELOG.md
src/types/user.rs

Similar to `is_anonymous` and `is_channel` functions added in #151, `User::is_telegram` checks for yet another special user.

Add `User::is_telegram` function

---

CHANGELOG.md
src/net/request.rs

This PR partially reverts #180 that caused `get_updates` timeouts because instead of increasing timeout it set it, see https://github.com/teloxide/teloxide/issues/526.
To properly fix the issue we need https://github.com/seanmonstar/reqwest/pull/1477, but we shouldn't block other issues/features on it, so I've decided to partially revert #180 for the time being.

Revert "better timeouts"

---

CHANGELOG.md
src/requests/has_payload.rs

`HasPayload::with_payload_mut` allows to easily apply multiple changes to the payload without calling `payload_mut()` multiple times and creating temporary variable for the request. e.g.:
```rust
// without `with_payload_mut`
{
let mut req = bot.set_webhook(url.clone());
req.payload_mut().certificate = certificate.take();
req.payload_mut().drop_pending_updates = drop_pending_updates;
req.send().await?;
}
// with `with_payload_mut`
bot
.set_webhook(url.clone())
.with_payload_mut(|payload| {
payload.certificate = certificate.take();
payload.drop_pending_updates = drop_pending_updates;
})
.send()
.await?
```

Add `HasPayload::with_payload_mut` function

---

CHANGELOG.md
Cargo.toml
src/bot/download.rs
src/errors.rs
src/net/request.rs

This fixes a potential[^1] security vulnerability -- if bot shows errors from teloxide to the user & for some reason network error happened[^2] the url of the request would be included in the error. Since TBA includes bot token in the error this may lead to token leakage.
This PR fixes that issue by removing the token from the urls of `reqwest::Error`, we try to redact only the token, but if we fail we remove the whole url.
This can be tested by using a very low timeout value for the http reqwest client:
```rust
let client = reqwest::Client::builder()
.timeout(std::time::Duration::from_millis(1))
.build()
.unwrap();
let bot = Bot::from_env_with_client(client).auto_send();
// see if the token is redacted when network error (timeout) happens
// while sending common requests
let _ = …
```

Hide bot token in errors

---

CHANGELOG.md
src/prelude.rs

I'm not entirely sure if we should do this, but this should simplify code that takes ids from external sources as integers.
I thought that that may be a good idea while working on the book.
This example currently needs an import of `ChatId`:
```rust
// replace 0 with your user id
let your_id = 0;
bot.send_message(ChatId(your_id), "Hi!")
// `.await` is needed to wait for an async operation
// `?` propagates possible errors
.await?;
```

Add `ChatId` and `UserId` to the prelude

---

src/adaptors/throttle/worker.rs

"Blocking on queue" literally means "nothing is happening, waiting until something happens". There is no reason to warn users about that.

Remove `log::warn!` from throttle implementation

---

CHANGELOG.md
src/types/file.rs

Fix deserialization of `File` when `file_path` or `file_size` are missing.
Telegram docs: https://core.telegram.org/bots/api#file

Fix deserialization of `File`

---

CHANGELOG.md
src/types/user.rs

Fix the following error:
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: !self.id.is_channel() ||\n    (self.is_bot && self.first_name == \"Group\" && self.last_name.is_none() &&\n            self.username.as_deref() == Some(\"GroupAnonymousBot\"))', /home/kezi/.cargo/registry/src/github.com-1ecc6299db9ec823/teloxide-core-0.6.1/src/types/user.rs:89:9
```

Fix is_channel assert

---

src/types/animation.rs
src/types/audio.rs
src/types/document.rs
src/types/file.rs
src/types/passport_file.rs
src/types/photo_size.rs
src/types/sticker.rs
src/types/video.rs
src/types/video_note.rs
src/types/voice.rs

Previously it wasn't clear in which unit file size was provided.

Improve documentation of `file_size` fields

---

CHANGELOG.md
Cargo.toml
examples/erased.rs
examples/self_info.rs
src/adaptors/throttle/settings.rs
src/types/message.rs
src/types/message_entity.rs

This PR resolves the long standing issue of "how to use message entities if their offsets are in UTF-16 and Rust uses UTF-8".
I've also fixed a couple of issues with documentation and examples, I'll be sure to make CI check them too later =.=

Implement message entity parsing

---

CHANGELOG.md
src/types/message.rs

This PR aims to fix a bug in Message::parse_caption_entities caused by using the text and text entities to parse the caption entities, instead of the caption and the caption entities.

Bugfix: fix Message::parse_caption_entities

---

CHANGELOG.md
src/types/inline_keyboard_button.rs

- Make `InlineKeyboardButtonKind::Pay.0` have type `True`
- Add more constructors to `InlineKeyboardButton`
- Make code in `inline_keyboard_button.rs` nicer
- Remove useless `InlineKeyboardButton::{text, kind}`
- Document `InlineKeyboardButton` constructors
- Update changelog

`InlineKeyboardButton` cleanup

---

CHANGELOG.md
src/net/download.rs
src/payloads/upload_sticker_file.rs
src/types/animation.rs
src/types/audio.rs
src/types/document.rs
src/types/file.rs
src/types/passport_file.rs
src/types/photo_size.rs
src/types/sticker.rs
src/types/video.rs
src/types/video_note.rs
src/types/voice.rs

This, _I think_, finally fixes issues with `file_size` and `file_path`.
By adding `FileMeta` we can
- Remove annoying `Option<>` for `file_path`
- Keep nice field access
- Keep deserialization correct
... all without confusing generics!
---
As a side-note: I've re-read telegram documentation, and `file_size` may not fit in 32 bit _signed_ integer. 32 bit unsigned integers are fine, actually (4GB max file size).

Properly fix file size/path

---

CHANGELOG.md
src/errors.rs

Adds the following impls:
```rust
impl From<ApiError> for RequestError { ... }
impl From<DownloadError> for RequestError { ... }
impl From<std::io::Error> for RequestError { ... }
```
Resolves https://github.com/teloxide/teloxide/issues/609

Implement `From<_> for RequestError` for more types

---

CHANGELOG.md
src/adaptors/erased.rs

`#[derive(Clone)]` added an unnecessary bound `E: Clone` that in practice made `ErasedRequester` not cloneable since `RequestError` doesn't implement `Clone`, this PR fixes that.

Fix `Clone` implementation for `ErasedRequester`

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
examples/erased.rs
examples/self_info.rs
rust-toolchain.toml
src/adaptors.rs
src/adaptors/auto_send.rs
src/adaptors/cache_me.rs
src/adaptors/erased.rs
src/adaptors/throttle/request.rs
src/adaptors/throttle/worker.rs
src/adaptors/trace.rs
src/bot.rs
src/codegen.rs
src/lib.rs
src/net/download.rs
src/requests/json.rs
src/requests/multipart.rs
src/requests/request.rs
src/requests/requester.rs
src/requests/requester_ext.rs

As the title implies, this PR uses `IntoFuture` to allow `.await`ing any request. No need for `AutoSend`!

Allow `.await`ing arbitrary requests!

---

CHANGELOG.md
src/types/animation.rs
src/types/audio.rs
src/types/document.rs
src/types/passport_file.rs
src/types/photo_size.rs
src/types/video.rs
src/types/video_note.rs
src/types/voice.rs

TL;DR, before:
```rust
pub struct Struct {
/// An identifier for this file.
pub file_id: String,
/// Unique identifier for this file, which is supposed to be the same over
/// time and for different bots. Can't be used to download or reuse the
/// file.
pub file_unique_id: String,
/// File size in bytes.
#[serde(default = "crate::types::file::file_size_fallback")]
pub file_size: u32,
// other fields...
}
```
after:
```rust
pub struct Struct {
/// Metadata of the {media} file.
#[deref]
#[serde(flatten)]
pub file: FileMeta,
// other fields...
}
```
-----
I'm not **certain** that we should do this refactoring, but reusing `FileMeta` seems nice.
In some cases we can even use `PhotoSize` but I don't think it's worth it (also **Photo**Size for videos would be confusing, I think).

Replace `file_{[unique_]id,size}` fields with `FileMeta`

---

.cargo/config.toml

You love to see a config option silently ignored because you've misplaced it 🥲

Fix how we set `rustdocflags` in the cargo config

---

CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

Now with TBA 6.2 supported and `.await` just working (tm) on requests!
While I'm not sure how fast can we finish work on the next release of `teloxide-macros` and `teloxide`, I don't think there are a lot of reasons to delay release of `teloxide-core`. We could stuff it with breaking changes forever, but we also need to draw the line somewhere.

Dump version `0.7.1` -> `0.8.0`
